import { NextRequest, NextResponse } from 'next/server'
import { PrismaClient } from '@prisma/client'
import * as XLSX from 'xlsx'
import mammoth from 'mammoth'
import * as pdfParse from 'pdf-parse'

const prisma = new PrismaClient()

// 模拟AI分析文件结构并生成规则
export async function analyzeFileStructure(buffer: ArrayBuffer, fileName: string, fileType: 'excel' | 'pdf' | 'word') {
  try {
    let rawData: any = {}
    let suggestions: any = {}

    if (fileType === 'excel') {
      const workbook = XLSX.read(buffer, { type: 'array' })
      const sheet = workbook.Sheets[workbook.SheetNames[0]]
      const data = XLSX.utils.sheet_to_json(sheet, { header: 1 }) as any[][]

      rawData = {
        sheetCount: workbook.SheetNames.length,
        sheetNames: workbook.SheetNames,
        totalRows: data.length,
        totalColumns: data[0]?.length || 0,
        sampleRows: data.slice(0, 20)
      }

      // AI分析：智能检测表头行
      const headerRowIndex = detectHeaderRow(data)
      const headers = data[headerRowIndex] || []

      // AI分析：检测数据结构
      const dataStartRow = headerRowIndex + 1
      const hasExternalCode = headers.some((h: any) => 
        String(h || '').includes('单号') || 
        String(h || '').includes('编号') || 
        String(h || '').includes('订单')
      )
      const hasRecipient = headers.some((h: any) => 
        String(h || '').includes('收货人') || 
        String(h || '').includes('收件人') || 
        String(h || '').includes('电话')
      )

      suggestions = {
        recommendedHeaderRow: headerRowIndex,
        recommendedDataStartRow: dataStartRow,
        recommendedDataEndRow: data.length - 1,
        hasExternalCode,
        hasRecipient,
        headerColumns: headers.slice(0, Math.min(20, headers.length)),
        fieldMappings: generateFieldMappings(headers),
        structure: {
          type: 'standard', // standard | matrix | card | multi-sheet
          multiSheet: workbook.SheetNames.length > 1,
          mergedCells: false,
          hasFooter: false
        }
      }
    } else if (fileType === 'pdf') {
      const bufferObj = Buffer.from(buffer)
      const pdfData = await (pdfParse as any)(bufferObj)
      rawData = {
        pages: pdfData.numpages,
        textLength: pdfData.text.length,
        sampleText: pdfData.text.substring(0, 2000)
      }
      suggestions = {
        structure: { type: 'pdf', pages: pdfData.numpages },
        fieldMappings: []
      }
    } else if (fileType === 'word') {
      const { value } = await mammoth.extractRawText({ arrayBuffer: buffer })
      rawData = {
        textLength: value.length,
        sampleText: value.substring(0, 2000)
      }
      suggestions = {
        structure: { type: 'word' },
        fieldMappings: []
      }
    }

    // 生成推荐规则
    const recommendedRule = {
      name: `自动生成规则 - ${fileName}`,
      description: '由AI分析文件结构自动生成的解析规则',
      structure: suggestions.structure || {},
      headerRow: suggestions.recommendedHeaderRow || 0,
      dataStartRow: suggestions.recommendedDataStartRow || 1,
      dataEndRow: suggestions.recommendedDataEndRow || -1,
      fieldMappings: suggestions.fieldMappings || [],
      confidence: 0.8,
      isAutoGenerated: true
    }

    return {
      success: true,
      fileName,
      fileType,
      rawData,
      analysis: suggestions,
      recommendedRule,
      message: '文件结构分析完成，请确认或调整规则后进行解析'
    }
  } catch (error: any) {
    console.error('AI分析失败:', error)
    return {
      success: false,
      error: '文件分析失败',
      details: error.message
    }
  }
}

// 智能检测表头行
function detectHeaderRow(data: any[][]) {
  const keywords = [
    '编码', '编号', 'SKU', '名称', '数量', '规格', '门店', 
    '收货', '电话', '地址', '单价', '金额', '日期', '单号'
  ]

  let bestRow = 0
  let bestScore = 0

  // 检测前20行
  for (let i = 0; i < Math.min(20, data.length); i++) {
    const row = data[i]
    if (!row || row.length === 0) continue

    let score = 0
    const rowStr = row.map(c => String(c || '')).join('')

    // 计算关键词匹配度
    for (const keyword of keywords) {
      if (rowStr.includes(keyword)) {
        score++
      }
    }

    // 有序号列加分
    if (rowStr.includes('序号') || rowStr.includes('NO') || rowStr.includes('No')) {
      score += 3
    }

    // 行列较短（说明是标题行）
    if (row.length <= 50) {
      score += 1
    }

    if (score > bestScore) {
      bestScore = score
      bestRow = i
    }
  }

  return bestRow
}

// 根据表头生成字段映射建议
function generateFieldMappings(headers: any[]) {
  const mappings: any[] = []
  const fieldKeywords: Record<string, string[]> = {
    externalCode: ['单号', '编号', '订单号', '配送单号', '出库单号'],
    skuCode: ['编码', '编号', 'SKU', '条码', '货号'],
    skuName: ['名称', '品名', '商品名称', '货品名称'],
    quantity: ['数量', '件数', 'Qty', '发货数量'],
    specification: ['规格', '规格型号', '型号', '单位'],
    storeName: ['门店', '店铺', '收货门店', '仓库'],
    recipientName: ['收货人', '收件人', '姓名', '联系人'],
    recipientPhone: ['电话', '手机', '联系电话'],
    recipientAddress: ['地址', '收货地址', '配送地址'],
    remarks: ['备注', '说明', '备注信息']
  }

  headers.forEach((header, index) => {
    const headerStr = String(header || '').trim()
    if (!headerStr) return

    for (const [field, keywords] of Object.entries(fieldKeywords)) {
      for (const keyword of keywords) {
        if (headerStr.includes(keyword) || headerStr === keyword) {
          mappings.push({
            field,
            source: headerStr,
            columnIndex: index,
            sourceType: 'column',
            confidence: headerStr.includes(keyword) ? 0.9 : 0.7,
            isAutoGenerated: true
          })
          break
        }
      }
    }
  })

  return mappings
}

// 使用规则解析文件
export function parseWithRule(
  buffer: ArrayBuffer, 
  rule: {
    headerRow: number
    dataStartRow: number
    dataEndRow: number
    fieldMappings: any[]
    structure: any
  }
) {
  const workbook = XLSX.read(buffer, { type: 'array' })
  const parsedData: any[] = []

  for (const sheetName of workbook.SheetNames) {
    const sheet = workbook.Sheets[sheetName]
    const data = XLSX.utils.sheet_to_json(sheet, { header: 1 }) as any[][]

    // 如果是-1表示到末尾
    const endRow = rule.dataEndRow === -1 ? data.length - 1 : rule.dataEndRow

    // 构建列索引映射
    const colIndexMap: Record<string, number> = {}
    for (const mapping of rule.fieldMappings) {
      if (mapping.sourceType === 'column') {
        // 优先使用列索引
        if (mapping.columnIndex !== undefined) {
          colIndexMap[mapping.field] = mapping.columnIndex
        }
        // 否则通过列名查找
        else if (mapping.source) {
          const headerRow = data[rule.headerRow] || []
          for (let i = 0; i < headerRow.length; i++) {
            if (String(headerRow[i] || '').trim() === mapping.source) {
              colIndexMap[mapping.field] = i
              break
            }
          }
        }
      }
    }

    // 解析数据行
    for (let i = rule.dataStartRow; i <= endRow && i < data.length; i++) {
      const row = data[i]
      if (!row) continue

      // 跳过空行
      if (row.every(cell => !cell || String(cell).trim() === '')) {
        continue
      }

      const item: any = {}

      for (const [field, colIdx] of Object.entries(colIndexMap)) {
        let value = row[colIdx as number]
        if (value === undefined || value === null) continue

        // 数量字段转换为数字
        if (field === 'quantity') {
          value = parseInt(String(value)) || 0
        } else {
          value = String(value).trim()
        }

        item[field] = value
      }

      // 只有包含SKU编码或名称的行才添加
      if (item.skuCode || item.skuName) {
        parsedData.push(item)
      }
    }
  }

  return parsedData
}

// 解析API
export async function POST(request: NextRequest) {
  try {
    const formData = await request.formData()
    const file = formData.get('file') as File | null
    const ruleId = formData.get('ruleId') as string | null
    const analyze = formData.get('analyze') as string | null

    if (!file) {
      return NextResponse.json({ error: '请上传文件' }, { status: 400 })
    }

    const bytes = await file.arrayBuffer()
    const fileName = file.name.toLowerCase()

    // 判断文件类型
    let fileType: 'excel' | 'pdf' | 'word' = 'excel'
    if (fileName.endsWith('.pdf')) {
      fileType = 'pdf'
    } else if (fileName.endsWith('.docx') || fileName.endsWith('.doc')) {
      fileType = 'word'
    }

    // 如果需要分析文件结构（AI生成规则）
    if (analyze === 'true') {
      const analysis = await analyzeFileStructure(bytes, file.name, fileType)
      return NextResponse.json(analysis)
    }

    // 如果没有规则ID，返回分析结果
    if (!ruleId) {
      const analysis = await analyzeFileStructure(bytes, file.name, fileType)
      return NextResponse.json(analysis)
    }

    // 有规则ID，使用规则解析
    const rule = await prisma.parsingRule.findUnique({
      where: { id: ruleId }
    })

    if (!rule) {
      return NextResponse.json({ error: '规则不存在' }, { status: 404 })
    }

    const ruleConfig = {
      headerRow: 0,
      dataStartRow: rule.structure?.dataStartRow || 1,
      dataEndRow: rule.structure?.dataEndRow || -1,
      fieldMappings: rule.fieldMappings || [],
      structure: rule.structure || {}
    }
    let parsedData: any[] = []

    if (fileType === 'excel') {
      parsedData = parseWithRule(bytes, ruleConfig)
    } else if (fileType === 'pdf') {
      // PDF解析逻辑
      const bufferObj = Buffer.from(bytes)
      const pdfData = await (pdfParse as any)(bufferObj)
      const lines = pdfData.text.split('\n')

      for (const line of lines) {
        const trimmed = line.trim()
        if (trimmed.length > 10 && !trimmed.includes('合计') && !trimmed.includes('总计')) {
          parsedData.push({
            skuCode: '',
            skuName: trimmed.substring(0, 100),
            quantity: 1
          })
        }
      }
    } else if (fileType === 'word') {
      // Word解析逻辑
      const { value } = await mammoth.extractRawText({ arrayBuffer: bytes })
      const lines = value.split('\n')

      for (const line of lines) {
        const trimmed = line.trim()
        if (trimmed.length > 5) {
          parsedData.push({
            skuCode: '',
            skuName: trimmed.substring(0, 100),
            quantity: 1
          })
        }
      }
    }

    return NextResponse.json({
      success: true,
      data: parsedData,
      total: parsedData.length,
      message: `成功解析 ${parsedData.length} 条数据`
    })
  } catch (error: any) {
    console.error('解析错误:', error)
    return NextResponse.json({
      error: '解析失败',
      details: error.message
    }, { status: 500 })
  } finally {
    await prisma.$disconnect()
  }
}
